### PR TITLE
fix typo, style guide updates

### PR DESCRIPTION
**Pull request by jeremyfiel**
I realize the style guide changes may not jive with your cli flag naming, but the official style guide defines how to reference each of the specifications and the artifacts associated with them.

* Updated usage of the name Overlay, per the [Overlay style guide](https://github.com/OAI/Overlay-Specification/blob/main/CONTRIBUTING.md#style-guide-for-overlay-specification)
* Updated the usage of OpenAPI `Description`, per the [OpenAPI style guide](https://spec.openapis.org/oas/v3.0.4#introduction)

### CODE REVIEW

**Comment by micovery** [comment]
Hey @jeremyfiel , thanks for the PR.

I was not aware of the terminology "OpenAPI description", I had to go and look it up, and sure enough that's what they are calling it now over at: https://learn.openapis.org/specification/structure.html#structure-of-an-openapi-description.


There is also the naming of the CLI flags for some commands that have `spec` in the name.

It will be a little weird that only this page uses the "OpenAPI description" term vs all other pages using "OpenAPI spec" term, but it's a good start.

**Comment by jeremyfiel** [comment]
Ya i figured it may be a small clash

I tried to find all instances of them to change

**Comment by jeremyfiel** [comment]
tried to find all the references and renamed files

**Comment by micovery** [comment]
> tried to find all the references and renamed files

Hey, I've checked out your PR branch locally and ran the tests `go test ./...`, there a couple of test cases that are failing.

Let's get those fixed. If you want give me collaborator access on your fork of the repo, and I will add a commit with the test fixes. 

Alternatively, you can cherry-pick this commit: https://github.com/apigee/apigee-go-gen/commit/588c379cbbcdbd22a3c1df4ef90fba47230b004f into your branch, to get the test fixes.

To cherry-pick, first checkout your own patch-1 branch, and then do this:

```
git remote add micovery https://github.com/micovery/apigee-go-gen.git
git fetch micovery
git cherry-pick 588c379cbbcdbd22a3c1df4ef90fba47230b004f
```

**Comment by jeremyfiel** [comment]
this was updated, not sure if you saw the latest commit.

**Comment by micovery** [comment]
I've made the doc changes live (https://apigee.github.io/apigee-go-gen/). I will be doing a new binary and docker release sometime next week, as I have some other changes lined up.

Once again, thanks for the contribution!

**Pull request merged**
